-- ===========================================
-- COUNTRIES SEED DATA
-- ===========================================
-- Generated from REST Countries API data
-- Run this in Supabase SQL Editor after running roam-supabase.sql
-- 
-- This populates the countries table with all world countries including:
-- - ISO 3166-1 alpha-2 country codes
-- - Country names
-- - Continent classifications
-- - Flag SVG URLs

INSERT INTO countries (code, name, continent, flag_url) VALUES ('AF', 'Afghanistan', 'Asia', 'https://flagcdn.com/af.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AX', 'Åland Islands', 'Europe', 'https://flagcdn.com/ax.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AL', 'Albania', 'Europe', 'https://flagcdn.com/al.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DZ', 'Algeria', 'Africa', 'https://flagcdn.com/dz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AS', 'American Samoa', 'Oceania', 'https://flagcdn.com/as.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AD', 'Andorra', 'Europe', 'https://flagcdn.com/ad.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AO', 'Angola', 'Africa', 'https://flagcdn.com/ao.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AI', 'Anguilla', 'North America', 'https://flagcdn.com/ai.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AQ', 'Antarctica', 'Antarctica', 'https://flagcdn.com/aq.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AG', 'Antigua and Barbuda', 'North America', 'https://flagcdn.com/ag.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AR', 'Argentina', 'South America', 'https://flagcdn.com/ar.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AM', 'Armenia', 'Asia', 'https://flagcdn.com/am.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AW', 'Aruba', 'North America', 'https://flagcdn.com/aw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AU', 'Australia', 'Oceania', 'https://flagcdn.com/au.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AT', 'Austria', 'Europe', 'https://flagcdn.com/at.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AZ', 'Azerbaijan', 'Asia', 'https://flagcdn.com/az.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BS', 'Bahamas', 'North America', 'https://flagcdn.com/bs.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BH', 'Bahrain', 'Asia', 'https://flagcdn.com/bh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BD', 'Bangladesh', 'Asia', 'https://flagcdn.com/bd.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BB', 'Barbados', 'North America', 'https://flagcdn.com/bb.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BY', 'Belarus', 'Europe', 'https://flagcdn.com/by.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BE', 'Belgium', 'Europe', 'https://flagcdn.com/be.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BZ', 'Belize', 'North America', 'https://flagcdn.com/bz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BJ', 'Benin', 'Africa', 'https://flagcdn.com/bj.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BM', 'Bermuda', 'North America', 'https://flagcdn.com/bm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BT', 'Bhutan', 'Asia', 'https://flagcdn.com/bt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BO', 'Bolivia', 'South America', 'https://flagcdn.com/bo.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BQ', 'Caribbean Netherlands', 'North America', 'https://flagcdn.com/bq.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BA', 'Bosnia and Herzegovina', 'Europe', 'https://flagcdn.com/ba.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BW', 'Botswana', 'Africa', 'https://flagcdn.com/bw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BV', 'Bouvet Island', 'Antarctica', 'https://flagcdn.com/bv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BR', 'Brazil', 'South America', 'https://flagcdn.com/br.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IO', 'British Indian Ocean Territory', 'Asia', 'https://flagcdn.com/io.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VG', 'British Virgin Islands', 'North America', 'https://flagcdn.com/vg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BN', 'Brunei', 'Asia', 'https://flagcdn.com/bn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BG', 'Bulgaria', 'Europe', 'https://flagcdn.com/bg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BF', 'Burkina Faso', 'Africa', 'https://flagcdn.com/bf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BI', 'Burundi', 'Africa', 'https://flagcdn.com/bi.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KH', 'Cambodia', 'Asia', 'https://flagcdn.com/kh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CM', 'Cameroon', 'Africa', 'https://flagcdn.com/cm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CA', 'Canada', 'North America', 'https://flagcdn.com/ca.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CV', 'Cape Verde', 'Africa', 'https://flagcdn.com/cv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KY', 'Cayman Islands', 'North America', 'https://flagcdn.com/ky.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CF', 'Central African Republic', 'Africa', 'https://flagcdn.com/cf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TD', 'Chad', 'Africa', 'https://flagcdn.com/td.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CL', 'Chile', 'South America', 'https://flagcdn.com/cl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CN', 'China', 'Asia', 'https://flagcdn.com/cn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CX', 'Christmas Island', 'Asia', 'https://flagcdn.com/cx.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CC', 'Cocos (Keeling) Islands', 'Asia', 'https://flagcdn.com/cc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CO', 'Colombia', 'South America', 'https://flagcdn.com/co.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KM', 'Comoros', 'Africa', 'https://flagcdn.com/km.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CG', 'Republic of the Congo', 'Africa', 'https://flagcdn.com/cg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CD', 'DR Congo', 'Africa', 'https://flagcdn.com/cd.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CK', 'Cook Islands', 'Oceania', 'https://flagcdn.com/ck.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CR', 'Costa Rica', 'North America', 'https://flagcdn.com/cr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CI', 'Ivory Coast', 'Africa', 'https://flagcdn.com/ci.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HR', 'Croatia', 'Europe', 'https://flagcdn.com/hr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CU', 'Cuba', 'North America', 'https://flagcdn.com/cu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CW', 'Curaçao', 'North America', 'https://flagcdn.com/cw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CY', 'Cyprus', 'Europe', 'https://flagcdn.com/cy.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CZ', 'Czechia', 'Europe', 'https://flagcdn.com/cz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DK', 'Denmark', 'Europe', 'https://flagcdn.com/dk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DJ', 'Djibouti', 'Africa', 'https://flagcdn.com/dj.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DM', 'Dominica', 'North America', 'https://flagcdn.com/dm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DO', 'Dominican Republic', 'North America', 'https://flagcdn.com/do.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('EC', 'Ecuador', 'South America', 'https://flagcdn.com/ec.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('EG', 'Egypt', 'Africa', 'https://flagcdn.com/eg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SV', 'El Salvador', 'North America', 'https://flagcdn.com/sv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GQ', 'Equatorial Guinea', 'Africa', 'https://flagcdn.com/gq.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ER', 'Eritrea', 'Africa', 'https://flagcdn.com/er.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('EE', 'Estonia', 'Europe', 'https://flagcdn.com/ee.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SZ', 'Eswatini', 'Africa', 'https://flagcdn.com/sz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ET', 'Ethiopia', 'Africa', 'https://flagcdn.com/et.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FK', 'Falkland Islands', 'South America', 'https://flagcdn.com/fk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FO', 'Faroe Islands', 'Europe', 'https://flagcdn.com/fo.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FJ', 'Fiji', 'Oceania', 'https://flagcdn.com/fj.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FI', 'Finland', 'Europe', 'https://flagcdn.com/fi.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FR', 'France', 'Europe', 'https://flagcdn.com/fr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GF', 'French Guiana', 'South America', 'https://flagcdn.com/gf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PF', 'French Polynesia', 'Oceania', 'https://flagcdn.com/pf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TF', 'French Southern and Antarctic Lands', 'Antarctica', 'https://flagcdn.com/tf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GA', 'Gabon', 'Africa', 'https://flagcdn.com/ga.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GM', 'Gambia', 'Africa', 'https://flagcdn.com/gm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GE', 'Georgia', 'Asia', 'https://flagcdn.com/ge.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('DE', 'Germany', 'Europe', 'https://flagcdn.com/de.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GH', 'Ghana', 'Africa', 'https://flagcdn.com/gh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GI', 'Gibraltar', 'Europe', 'https://flagcdn.com/gi.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GR', 'Greece', 'Europe', 'https://flagcdn.com/gr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GL', 'Greenland', 'North America', 'https://flagcdn.com/gl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GD', 'Grenada', 'North America', 'https://flagcdn.com/gd.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GP', 'Guadeloupe', 'North America', 'https://flagcdn.com/gp.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GU', 'Guam', 'Oceania', 'https://flagcdn.com/gu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GT', 'Guatemala', 'North America', 'https://flagcdn.com/gt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GG', 'Guernsey', 'Europe', 'https://flagcdn.com/gg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GN', 'Guinea', 'Africa', 'https://flagcdn.com/gn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GW', 'Guinea-Bissau', 'Africa', 'https://flagcdn.com/gw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GY', 'Guyana', 'South America', 'https://flagcdn.com/gy.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HT', 'Haiti', 'North America', 'https://flagcdn.com/ht.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HM', 'Heard Island and McDonald Islands', 'Antarctica', 'https://flagcdn.com/hm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VA', 'Vatican City', 'Europe', 'https://flagcdn.com/va.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HN', 'Honduras', 'North America', 'https://flagcdn.com/hn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HK', 'Hong Kong', 'Asia', 'https://flagcdn.com/hk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('HU', 'Hungary', 'Europe', 'https://flagcdn.com/hu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IS', 'Iceland', 'Europe', 'https://flagcdn.com/is.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IN', 'India', 'Asia', 'https://flagcdn.com/in.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ID', 'Indonesia', 'Asia', 'https://flagcdn.com/id.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IR', 'Iran', 'Asia', 'https://flagcdn.com/ir.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IQ', 'Iraq', 'Asia', 'https://flagcdn.com/iq.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IE', 'Ireland', 'Europe', 'https://flagcdn.com/ie.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IM', 'Isle of Man', 'Europe', 'https://flagcdn.com/im.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IL', 'Israel', 'Asia', 'https://flagcdn.com/il.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('IT', 'Italy', 'Europe', 'https://flagcdn.com/it.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('JM', 'Jamaica', 'North America', 'https://flagcdn.com/jm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('JP', 'Japan', 'Asia', 'https://flagcdn.com/jp.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('JE', 'Jersey', 'Europe', 'https://flagcdn.com/je.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('JO', 'Jordan', 'Asia', 'https://flagcdn.com/jo.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KZ', 'Kazakhstan', 'Asia', 'https://flagcdn.com/kz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KE', 'Kenya', 'Africa', 'https://flagcdn.com/ke.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KI', 'Kiribati', 'Oceania', 'https://flagcdn.com/ki.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KW', 'Kuwait', 'Asia', 'https://flagcdn.com/kw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KG', 'Kyrgyzstan', 'Asia', 'https://flagcdn.com/kg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LA', 'Laos', 'Asia', 'https://flagcdn.com/la.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LV', 'Latvia', 'Europe', 'https://flagcdn.com/lv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LB', 'Lebanon', 'Asia', 'https://flagcdn.com/lb.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LS', 'Lesotho', 'Africa', 'https://flagcdn.com/ls.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LR', 'Liberia', 'Africa', 'https://flagcdn.com/lr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LY', 'Libya', 'Africa', 'https://flagcdn.com/ly.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LI', 'Liechtenstein', 'Europe', 'https://flagcdn.com/li.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LT', 'Lithuania', 'Europe', 'https://flagcdn.com/lt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LU', 'Luxembourg', 'Europe', 'https://flagcdn.com/lu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MO', 'Macau', 'Asia', 'https://flagcdn.com/mo.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MG', 'Madagascar', 'Africa', 'https://flagcdn.com/mg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MW', 'Malawi', 'Africa', 'https://flagcdn.com/mw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MY', 'Malaysia', 'Asia', 'https://flagcdn.com/my.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MV', 'Maldives', 'Asia', 'https://flagcdn.com/mv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ML', 'Mali', 'Africa', 'https://flagcdn.com/ml.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MT', 'Malta', 'Europe', 'https://flagcdn.com/mt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MH', 'Marshall Islands', 'Oceania', 'https://flagcdn.com/mh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MQ', 'Martinique', 'North America', 'https://flagcdn.com/mq.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MR', 'Mauritania', 'Africa', 'https://flagcdn.com/mr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MU', 'Mauritius', 'Africa', 'https://flagcdn.com/mu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('YT', 'Mayotte', 'Africa', 'https://flagcdn.com/yt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MX', 'Mexico', 'North America', 'https://flagcdn.com/mx.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('FM', 'Micronesia', 'Oceania', 'https://flagcdn.com/fm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MD', 'Moldova', 'Europe', 'https://flagcdn.com/md.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MC', 'Monaco', 'Europe', 'https://flagcdn.com/mc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MN', 'Mongolia', 'Asia', 'https://flagcdn.com/mn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ME', 'Montenegro', 'Europe', 'https://flagcdn.com/me.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MS', 'Montserrat', 'North America', 'https://flagcdn.com/ms.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MA', 'Morocco', 'Africa', 'https://flagcdn.com/ma.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MZ', 'Mozambique', 'Africa', 'https://flagcdn.com/mz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MM', 'Myanmar', 'Asia', 'https://flagcdn.com/mm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NA', 'Namibia', 'Africa', 'https://flagcdn.com/na.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NR', 'Nauru', 'Oceania', 'https://flagcdn.com/nr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NP', 'Nepal', 'Asia', 'https://flagcdn.com/np.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NL', 'Netherlands', 'Europe', 'https://flagcdn.com/nl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NC', 'New Caledonia', 'Oceania', 'https://flagcdn.com/nc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NZ', 'New Zealand', 'Oceania', 'https://flagcdn.com/nz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NI', 'Nicaragua', 'North America', 'https://flagcdn.com/ni.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NE', 'Niger', 'Africa', 'https://flagcdn.com/ne.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NG', 'Nigeria', 'Africa', 'https://flagcdn.com/ng.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NU', 'Niue', 'Oceania', 'https://flagcdn.com/nu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NF', 'Norfolk Island', 'Oceania', 'https://flagcdn.com/nf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KP', 'North Korea', 'Asia', 'https://flagcdn.com/kp.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MK', 'North Macedonia', 'Europe', 'https://flagcdn.com/mk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MP', 'Northern Mariana Islands', 'Oceania', 'https://flagcdn.com/mp.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('NO', 'Norway', 'Europe', 'https://flagcdn.com/no.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('OM', 'Oman', 'Asia', 'https://flagcdn.com/om.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PK', 'Pakistan', 'Asia', 'https://flagcdn.com/pk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PW', 'Palau', 'Oceania', 'https://flagcdn.com/pw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PS', 'Palestine', 'Asia', 'https://flagcdn.com/ps.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PA', 'Panama', 'North America', 'https://flagcdn.com/pa.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PG', 'Papua New Guinea', 'Oceania', 'https://flagcdn.com/pg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PY', 'Paraguay', 'South America', 'https://flagcdn.com/py.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PE', 'Peru', 'South America', 'https://flagcdn.com/pe.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PH', 'Philippines', 'Asia', 'https://flagcdn.com/ph.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PN', 'Pitcairn Islands', 'Oceania', 'https://flagcdn.com/pn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PL', 'Poland', 'Europe', 'https://flagcdn.com/pl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PT', 'Portugal', 'Europe', 'https://flagcdn.com/pt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PR', 'Puerto Rico', 'North America', 'https://flagcdn.com/pr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('QA', 'Qatar', 'Asia', 'https://flagcdn.com/qa.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('RE', 'Réunion', 'Africa', 'https://flagcdn.com/re.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('RO', 'Romania', 'Europe', 'https://flagcdn.com/ro.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('RU', 'Russia', 'Europe', 'https://flagcdn.com/ru.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('RW', 'Rwanda', 'Africa', 'https://flagcdn.com/rw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('BL', 'Saint Barthélemy', 'North America', 'https://flagcdn.com/bl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'https://flagcdn.com/sh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KN', 'Saint Kitts and Nevis', 'North America', 'https://flagcdn.com/kn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LC', 'Saint Lucia', 'North America', 'https://flagcdn.com/lc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('MF', 'Saint Martin', 'North America', 'https://flagcdn.com/mf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('PM', 'Saint Pierre and Miquelon', 'North America', 'https://flagcdn.com/pm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VC', 'Saint Vincent and the Grenadines', 'North America', 'https://flagcdn.com/vc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('WS', 'Samoa', 'Oceania', 'https://flagcdn.com/ws.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SM', 'San Marino', 'Europe', 'https://flagcdn.com/sm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ST', 'São Tomé and Príncipe', 'Africa', 'https://flagcdn.com/st.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SA', 'Saudi Arabia', 'Asia', 'https://flagcdn.com/sa.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SN', 'Senegal', 'Africa', 'https://flagcdn.com/sn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('RS', 'Serbia', 'Europe', 'https://flagcdn.com/rs.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SC', 'Seychelles', 'Africa', 'https://flagcdn.com/sc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SL', 'Sierra Leone', 'Africa', 'https://flagcdn.com/sl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SG', 'Singapore', 'Asia', 'https://flagcdn.com/sg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SX', 'Sint Maarten', 'North America', 'https://flagcdn.com/sx.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SK', 'Slovakia', 'Europe', 'https://flagcdn.com/sk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SI', 'Slovenia', 'Europe', 'https://flagcdn.com/si.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SB', 'Solomon Islands', 'Oceania', 'https://flagcdn.com/sb.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SO', 'Somalia', 'Africa', 'https://flagcdn.com/so.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ZA', 'South Africa', 'Africa', 'https://flagcdn.com/za.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GS', 'South Georgia', 'Antarctica', 'https://flagcdn.com/gs.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('KR', 'South Korea', 'Asia', 'https://flagcdn.com/kr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SS', 'South Sudan', 'Africa', 'https://flagcdn.com/ss.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ES', 'Spain', 'Europe', 'https://flagcdn.com/es.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('LK', 'Sri Lanka', 'Asia', 'https://flagcdn.com/lk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SD', 'Sudan', 'Africa', 'https://flagcdn.com/sd.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SR', 'Suriname', 'South America', 'https://flagcdn.com/sr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SJ', 'Svalbard and Jan Mayen', 'Europe', 'https://flagcdn.com/sj.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SE', 'Sweden', 'Europe', 'https://flagcdn.com/se.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('CH', 'Switzerland', 'Europe', 'https://flagcdn.com/ch.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('SY', 'Syria', 'Asia', 'https://flagcdn.com/sy.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TW', 'Taiwan', 'Asia', 'https://flagcdn.com/tw.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TJ', 'Tajikistan', 'Asia', 'https://flagcdn.com/tj.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TZ', 'Tanzania', 'Africa', 'https://flagcdn.com/tz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TH', 'Thailand', 'Asia', 'https://flagcdn.com/th.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TL', 'Timor-Leste', 'Asia', 'https://flagcdn.com/tl.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TG', 'Togo', 'Africa', 'https://flagcdn.com/tg.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TK', 'Tokelau', 'Oceania', 'https://flagcdn.com/tk.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TO', 'Tonga', 'Oceania', 'https://flagcdn.com/to.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TT', 'Trinidad and Tobago', 'North America', 'https://flagcdn.com/tt.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TN', 'Tunisia', 'Africa', 'https://flagcdn.com/tn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TR', 'Turkey', 'Asia', 'https://flagcdn.com/tr.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TM', 'Turkmenistan', 'Asia', 'https://flagcdn.com/tm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TC', 'Turks and Caicos Islands', 'North America', 'https://flagcdn.com/tc.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('TV', 'Tuvalu', 'Oceania', 'https://flagcdn.com/tv.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('UG', 'Uganda', 'Africa', 'https://flagcdn.com/ug.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('UA', 'Ukraine', 'Europe', 'https://flagcdn.com/ua.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('AE', 'United Arab Emirates', 'Asia', 'https://flagcdn.com/ae.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('GB', 'United Kingdom', 'Europe', 'https://flagcdn.com/gb.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('US', 'United States', 'North America', 'https://flagcdn.com/us.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('UM', 'United States Minor Outlying Islands', 'Oceania', 'https://flagcdn.com/um.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VI', 'United States Virgin Islands', 'North America', 'https://flagcdn.com/vi.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('UY', 'Uruguay', 'South America', 'https://flagcdn.com/uy.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('UZ', 'Uzbekistan', 'Asia', 'https://flagcdn.com/uz.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VU', 'Vanuatu', 'Oceania', 'https://flagcdn.com/vu.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VE', 'Venezuela', 'South America', 'https://flagcdn.com/ve.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('VN', 'Vietnam', 'Asia', 'https://flagcdn.com/vn.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('WF', 'Wallis and Futuna', 'Oceania', 'https://flagcdn.com/wf.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('EH', 'Western Sahara', 'Africa', 'https://flagcdn.com/eh.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('YE', 'Yemen', 'Asia', 'https://flagcdn.com/ye.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ZM', 'Zambia', 'Africa', 'https://flagcdn.com/zm.svg');
INSERT INTO countries (code, name, continent, flag_url) VALUES ('ZW', 'Zimbabwe', 'Africa', 'https://flagcdn.com/zw.svg');
